version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: django_web
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "7777:7777"
    env_file:
      - envs/.env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=django
      - POSTGRES_PASSWORD=1253
    ports:
      - "5432:5432"

#  bot:
#    build:
#      context: .
#      dockerfile: ./compose/django/Dockerfile
#    image: support_bot
#    command: python /app/Bot/main.py
#    volumes:
#      - .:/app
#    env_file:
#      - envs/.env
#    depends_on:
#      - db

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    logging:
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  static_volume:
  postgres_data:
  media_volume:
