version: '3.8'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: django_web
    command: /start
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - envs/.env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=django
      - POSTGRES_PASSWORD=1253
    ports:
      - "5432:5432"


volumes:
  postgres_data:
