name: Lint & Typecheck

on:
  push:
    branches: [ main, develop, "*" ]
  pull_request:

env:
  PYTHON_VERSION: "3.11"
  UV_VERSION: "0.7.2"

jobs:
  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install go-task
        run: uv tool install go-task-bin

      - name: Run Ruff lint
        run: uv run task lint

  typecheck:
    name: Mypy Type Check
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install go-task
        run: uv tool install go-task-bin

      - name: Run Mypy typecheck
        run: uv run task typecheck
