name: Telegram Notifications

on:
  pull_request:
    types:
      [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review_comment:
    types: [created]
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Telegram Gate
    runs-on: ubuntu-latest
    steps:
      - name: Notifier
        uses: ethyaan/tgate-action@v1.0.0
        if: always()
        with:
          token: ${{ secrets.TOKEN }}
          to: ${{ secrets.CHAT_ID }}
          disable_web_page_preview: true
          disable_notification: false
